import { api } from "../api-client.js";

export const positionTools = [
  { name: "list_positions", description: "List current open positions for a user's wallet.", schema: { type: "object", properties: { user_id: { type: "string" } }, required: ["user_id"] }, handler: ({ user_id }) => api.get("/v1/positions", { user_id }) },
  { name: "get_position", description: "Get position details for a specific market.", schema: { type: "object", properties: { user_id: { type: "string" }, market_slug: { type: "string" } }, required: ["user_id", "market_slug"] }, handler: async ({ user_id, market_slug }) => { const all = await api.get("/v1/positions", { user_id }); return all.find((p) => p.market_slug === market_slug) ?? null; } },
  { name: "get_position_pnl", description: "Get realized and unrealized PnL for a user's positions.", schema: { type: "object", properties: { user_id: { type: "string" } }, required: ["user_id"] }, handler: async ({ user_id }) => { const positions = await api.get("/v1/positions", { user_id }); return { realized: positions.reduce((s, p) => s + (p.realized_pnl ?? 0), 0), unrealized: positions.reduce((s, p) => s + (p.unrealized_pnl ?? 0), 0) }; } },
  { name: "list_fills", description: "List fill history for a user.", schema: { type: "object", properties: { user_id: { type: "string" }, limit: { type: "number", default: 100 } }, required: ["user_id"] }, handler: ({ user_id, limit = 100 }) => api.get("/v1/fills", { user_id, limit }) },
  { name: "get_fill", description: "Get a specific fill by ID.", schema: { type: "object", properties: { user_id: { type: "string" }, fill_id: { type: "number" } }, required: ["user_id", "fill_id"] }, handler: async ({ user_id, fill_id }) => { const fills = await api.get("/v1/fills", { user_id }); return fills.find((f) => f.id === fill_id) ?? null; } },
  { name: "get_portfolio_summary", description: "Get a summary of total positions, PnL, and active deployments.", schema: { type: "object", properties: { user_id: { type: "string" } }, required: ["user_id"] }, handler: async ({ user_id }) => { const [positions, fills, deployments] = await Promise.all([api.get("/v1/positions", { user_id }), api.get("/v1/fills", { user_id, limit: 1000 }), api.get("/v1/deployments", { user_id })]); return { open_positions: positions.length, total_realized_pnl: positions.reduce((s, p) => s + (p.realized_pnl ?? 0), 0), total_fills: fills.length, active_deployments: deployments.filter((d) => d.status === "active").length }; } },
];
