import { api } from "../api-client.js";

export const signalTools = [
  {
    name: "get_signals",
    description: "Get recent signals generated by a deployment. Each signal includes direction (bullish/bearish), confidence score, market name, reasoning, and suggested action.",
    schema: {
      type: "object",
      properties: {
        deployment_id: { type: "number", description: "Deployment to fetch signals for" },
        user_id: { type: "string", description: "The user's AlgoGlide user ID" },
        limit: { type: "number", description: "Max signals to return (default 10)", default: 10 },
      },
      required: ["deployment_id", "user_id"],
    },
    handler: async ({ deployment_id, user_id, limit = 10 }) =>
      api.get(`/v1/deployments/${deployment_id}/signals`, { user_id, limit }),
  },
  {
    name: "get_deployment_signals",
    description: "Get recent signals generated by a deployment with direction, confidence, and reasoning.",
    schema: {
      type: "object",
      properties: {
        deployment_id: { type: "number", description: "Deployment to fetch signals for" },
        user_id: { type: "string", description: "The user's AlgoGlide user ID" },
        limit: { type: "number", description: "Max signals to return (default 10)", default: 10 },
      },
      required: ["deployment_id", "user_id"],
    },
    handler: async ({ deployment_id, user_id, limit = 10 }) =>
      api.get(`/v1/deployments/${deployment_id}/signals`, { user_id, limit }),
  },
  {
    name: "get_signal_logs",
    description: "Get execution logs from a deployment. Useful for debugging strategy errors or tracing signal generation.",
    schema: {
      type: "object",
      properties: {
        deployment_id: { type: "number", description: "Deployment to fetch logs for" },
        user_id: { type: "string", description: "The user's AlgoGlide user ID" },
        limit: { type: "number", description: "Max log lines to return (default 50)", default: 50 },
      },
      required: ["deployment_id", "user_id"],
    },
    handler: async ({ deployment_id, user_id, limit = 50 }) =>
      api.get(`/v1/deployments/${deployment_id}/logs`, { user_id, limit }),
  },
];
